### PR TITLE
Move onto travis' newer infrastructure

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Just adds sudo: false

### CODE REVIEW

**Comment by weavejester** [comment]
You have a bunch of commits that aren't relevant to this PR mixed in. Maybe create a new branch from master and cherry-pick the commit in?

**Comment by SevereOverfl0w** [comment]
Yeah, I meant to put the other commit it's own branch & messed up, I need to go learn how to rewrite history a little!

**Comment by drusellers** [comment]
@SevereOverfl0w would you like some help with this?

**Comment by SevereOverfl0w** [comment]
@drusellers thanks, but I figured it out. I've been away for a little while, hence the quiet time.

This PR has now been rebased onto master so doesn't include any other commits.

**Comment by drusellers** [comment]
:+1:

**Pull request closed without merging**
