### PR TITLE
Explain the various metadata available

### PR DESCRIPTION
**Pull request by drusellers**
Based on issue #1 I'm hoping to provide a better introduction
to the functions for new users.

### CODE REVIEW

**Comment by weavejester** [comment]
I think this is a good idea. Could you remove the additional explanation from the commit message? I don't think it's necessary to justify a commit in the commit message itself.

Could you ensure the changes you make to the README are consistent with the existing formatting? So `###Metadata` should be `### Metadata`, and the lines should wrap at 80 characters. Also you have some random blockquotes (`>`) on some of the lines.

I also think that maybe **Metadata** should be its own section outside of usage, so `## Metadata`.

**Comment by drusellers** [comment]
The blockquotes are attempt to highlight what the core function of the meta data is and is a quote from you in the issue where we discussed this earlier. Happy to remove them, was just using them as a formatting function. Fixes will be posted shortly.

**Comment by drusellers** [comment]
Updated. The only comment not addressed was the blockquotes

**Comment by weavejester** [comment]
Thanks for the update. Could you remove the blockquotes anyway? While they might help formatting, they don't really make any semantic sense.

**Comment by drusellers** [comment]
Can do.

**Comment by drusellers** [comment]
Done

**Pull request merged**
